// Manter em sincronia com frontend
export const Acao = {
    N: "N",
    S: "S",
    L: "L",
    O: "O",
    NO: "NO",
    SE: "SE",
    NE: "NE",
    SO: "SO",
    Subir: "SUBIR",
    Descer: "DESCER",
    Entrar: "ENTRAR",
    Sair: "SAIR",

    Olhar: "OLHAR",
    Pegar: "PEGAR",
    Largar: "LARGAR",
    Mochila: "MOCHILA",

    Abrir: "ABRIR",
    Fechar: "FECHAR",
    Acender: "ACENDER",
    Apagar: "APAGAR",
    Ligar: "LIGAR",
    Desligar: "DESLIGAR",
    Mover: "MOVER",
    Empurrar: "EMPURRAR",
    Comer: "COMER",
    Beber: "BEBER",
    Cheirar: "CHEIRAR",
    Ouvir: "OUVIR",
    Tocar: "TOCAR",
    Escrever: "ESCREVER",
    Ler: "LER",

    Jogar: "JOGAR",
    Destrancar: "DESTRANCAR",
    Trancar: "TRANCAR",
    Colocar: "COLOCAR",
    Virar: "VIRAR",
    Amarrar: "AMARRAR",
    Desamarrar: "DESAMARRAR",
    Cortar: "CORTAR",
    Quebrar: "QUEBRAR",
    Atacar: "ATACAR",
    Dar: "DAR",
    Falar: "FALAR",
    Inflar: "INFLAR",
    Cavar: "CAVAR",
    Queimar: "QUEIMAR",

    Oi: "OI",
    Gritar: "GRITAR",
    Pular: "PULAR",
    Dormir: "DORMIR",

    Ir: "IR",
    Artigos: "ARTIGOS",
    Preposicoes: "PREPS",
    Contracoes: "CONTR",

    Usar: "USAR",
    Chao: "CHAO",

    $Descricao: "$DESCRICAO",
} as const;
export type AcaoValue = typeof Acao[keyof typeof Acao];